### ISSUE TITLE
error: cannot find symbol DaggerMyAppComponent.builder()

### ISSUE THREAD

**Issue by ColtonIdle** [JakeWharton/dagger-reflect#191]
I added in the "partial reflection" dependencies only and removed my previous dagger dependencies.

aka my dependencies looks like this

```
dependencies {
    kaptDebug 'com.jakewharton.dagger:dagger-reflect-compiler:0.2.0'
    debugImplementation 'com.jakewharton.dagger:dagger-reflect:0.2.0'
}
```
So you can see I completely remove the "if ide" check and everything else. I have a simple dagger implementation (simple single android app with a single android app module, only a single dagger component, 2 dagger modules, and basically just using constructor injection. Nothing crazy)

`MyApp.java:207: error: cannot find symbol
DaggerMyAppComponent.builder()`

It looks like my `builder()` isn't available on the generated `DaggerMyAppComponent`. If I'm reading the docs correctly, I don't have to change anything with the partial reflection route. Is there something wrong I'm doing?

**Comment by TWiStErRob** [comment]
From what you explained I presume you're using the implicit builder from standard Dagger. i.e.
```kotlin
@Component(modules = [...])
interface MyAppComponent { ... }
```
where `{ ... }` doesn't contain `@Component.Builder interface Builder { ... }`, nor a `@Component.Factory`.

From what I can see reading the sources and tests at https://github.com/JakeWharton/dagger-reflect/tree/master/reflect-compiler/src in that case you'll get a `create` method, but not a `builder`:
https://github.com/JakeWharton/dagger-reflect/blob/7820187d0ae56fc718eabed28aa8b1aed2a39fa7/reflect-compiler/src/main/java/dagger/reflect/compiler/DaggerReflectCompiler.java#L146-L151

https://github.com/JakeWharton/dagger-reflect/blob/7820187d0ae56fc718eabed28aa8b1aed2a39fa7/reflect-compiler/src/test/java/dagger/reflect/compiler/DaggerReflectCompilerTest.java#L66-L73

@JakeWharton I think this default builder generation is not implemented in `reflect-compiler`, see here:
https://dagger.dev/api/latest/dagger/Component.html#instantiation
> If neither exists, Dagger will generate a builder type that has a method to set each of the modules() and component dependencies() named with the lower camel case version of the module or dependency type.
> In either case, the Dagger-generated component type will have a static method, named either builder() or factory(), that returns a builder or factory instance.

@ColtonIdle if your `@Module`s don't have constructor parameters, then you can use `.create()` instead of `.builder().build()`, but if they do, you'll need to add a `Builder` as described below to trigger the `.builder()` method generation in `reflect-compiler`: https://dagger.dev/api/latest/dagger/Component.Builder.html#instantiation

**Comment by ColtonIdle** [comment]
@TWiStErRob thanks for the detailed response!

> if your @Modules don't have constructor parameters

My modules do have a constructor parameter, so it seems like I need to add the builder myself?

This is what I currently have:

```
@Singleton
@Component(
        modules = {
                NetworkModule.class
        }
)

public interface MyAppComponent {
    void inject(MyActivity inject);
}
```

I updated this to

```
@Singleton
@Component(
        modules = {
                NetworkModule.class
        }
)

public interface MyAppComponent {
    @Component.Builder
    interface Builder {
        Builder networkModule(NetworkModule module);
        AppComponent build();
    }

    void inject(MyActivity inject);
}
```

and my app seems to compile just fine. I _really_ don't understand two things though.

1. Why is this needed? I'm new to dagger, so should I have known that I should have been doing this for some reason?

2. I noticed in https://dagger.dev/api/latest/dagger/Component.Builder.html it includes `      @BindsInstance Builder foo(Foo foo);` As you can see above, I don't do that. Should I have a `@BindInstance` somewhere? How does this relate to @JakeWharton comment here https://github.com/JakeWharton/dagger-reflect/issues/4 "but in general you should refactor to @BindsInstance and stateless modules." Anyone know why I should be using `BindInstance`, and what's a stateless module?

**Comment by TWiStErRob** [comment]
Re 1) see the part I wrote for Jake above, Dagger and Dagger reflect behave differently, that's my best informed guess. Note: the spec/doc of `Component` is pretty dense, every word has meaning and implications.
Dagger offers many ways to achieve the same thing. Neither one is really wrong, but there are some best practices. I don't know where you would get them though, I don't think I've seen a comprehensive and authorative source yet. The Dagger doc on the website is pretty good though (except the infamous Thermosiphon), worth reading it once at least.

Re 2) `@BindsInstance` is more efficient and easier to see/maintain than stateful modules (instance fields). A stateless module is a module that you can make an `object` or an `abstract class` with only `static` methods, in the best case an `interface` with only `@Binds` methods. Meaning, you don't need an instance for it and in many cases you can't even have an instance of it.

If you go stateless, the line `Builder networkModule(NetworkModule module);` becomes unnecessary and you can very likely even use a `Factory` which has further benefits.

**Comment by ColtonIdle** [comment]
Apparently the new hotness is to use a factory which I didn't know because I'm new to dagger. Closing
